Hillclimb locations model fix
y-ooshima/hirukura pull request #7
Opened 2021-05-18 13:06 UTC by y-ooshima

・モデル名を修正しました。(Mountainsに変更しました。)
・修正に合わせて関連のある変数名も修正しました。

2021-05-19 01:19 UTC, ichikawa-riku requested changes
コメントしました

2021-05-19 01:19 UTC, ichikawa-riku commented on app/Http/Controllers/PostController.php
> +    public function mountains_search(Request $request)
searchだけでよいと思います。

2021-05-19 01:19 UTC, ichikawa-riku commented on database/migrations/2021_05_17_141347_create_mountains_table.php
>  use Illuminate\Database\Schema\Blueprint;
今回はOKですが、マイグレーションファイルは消さないで追加するのが基本です。

2021-05-19 01:19 UTC, ichikawa-riku commented on app/Http/Controllers/PostController.php
> +        $mountains = Mountains::findOrFail($mountains_id);
$montains => $montain

2021-05-19 01:19 UTC, ichikawa-riku commented on resources/views/posts/show.blade.php
> +                        <h4 class="card-title text-center">峠名: {{ $mountains->name }} </h4>
$montains => $montain

2021-05-19 01:19 UTC, ichikawa-riku commented on routes/web.php
> +Route::post('/searching', 'PostController@mountains_search');
method名変更したらここも変更

2021-05-19 11:52 UTC, y-ooshima commented on database/migrations/2021_05_17_141347_create_mountains_table.php
>  use Illuminate\Database\Schema\Blueprint;
承知致しました。

2021-05-19 12:12 UTC, ichikawa-riku requested changes
コメントしました

2021-05-19 12:12 UTC, ichikawa-riku commented on app/Http/Controllers/PostController.php
> +        $mountain = Mountains::all();
どんな動作にしたいか分からないですが、
ここはビュー表示ではなくリダイレクトが良いかと思います。

2021-05-19 12:34 UTC, y-ooshima commented on app/Http/Controllers/PostController.php
> +        $mountain = Mountains::all();
リダイレクトに修正します。
（削除後に開くページをトップ画面に変更します。）

2021-05-19 12:43 UTC, ichikawa-riku requested changes
postsテーブルのカラム名も変更しましょう。
マイグレーションファイルは、修正ではなく、
カラム追加のマイグレーションファイルを作成しましょう。

https://github.com/y-ooshima/hirukura/blob/47a3da25ca11686cb2575311ab96261971892d3a/app/Http/Controllers/PostController.php#L50

https://github.com/y-ooshima/hirukura/blob/47a3da25ca11686cb2575311ab96261971892d3a/resources/views/users/create.blade.php#L29

2021-05-20 15:10 UTC, ichikawa-riku requested changes
コメントしました

2021-05-20 15:10 UTC, ichikawa-riku commented on database/migrations/2021_05_19_140632_create_add_posts_table.php
> +<?php
up()とdown()の記述が違います。

up()はmigrationが実行されたときに走る処理
down()はmigrationをrollbackしたときに走る処理です

なので今回のケースで考えると、
upには、
mountain_idをカラム追加する処理
hillclimb_location_idを消す処理

downには、
mountain_idを削除する処理
hillclimb_location_idをカラム追加する処理
になります。

こちら実行はしましたでしょうか？
おそらく、hillclimb_location_idが消えてないと思います。

2021-05-21 13:34 UTC, y-ooshima commented on database/migrations/2021_05_19_140632_create_add_posts_table.php
> +<?php
ご連絡有難う御座います。
確認しましたが消えていませんでした。
修正いたします。

2021-05-21 17:09 UTC, ichikawa-riku approved these changes
![image](https://user-images.githubusercontent.com/47102378/119173835-c22b0680-baa2-11eb-84b7-22f723c142af.png)

2021-05-22 00:31 UTC, merged