Post view delete
y-ooshima/hirukura pull request #8
Opened 2021-05-22 06:44 UTC by y-ooshima

・確認用で使用していたviewのpost_directoryを削除しました。

2021-05-22 07:17 UTC, ichikawa-riku requested changes
contorollerとビューはファイル名やディレクトリ名で関連性がわかるようにしてください。

2021-05-22 07:17 UTC, ichikawa-riku commented on app/Http/Controllers/PostController.php
> +        return view('users.past_review_edit', compact('post','mountain','user'));
postコントローラーからusersのビューを呼ぶのはあまり良くない実装です。

2021-05-22 07:17 UTC, ichikawa-riku commented on app/Http/Controllers/PostController.php
> +        return redirect()->route('review.show', ['id' => $post->id]);
postコントローラーからreviewを呼ぶ？
postに統一で良いと思いますが、
なにか理由があるのでしょうか？

2021-05-22 07:17 UTC, ichikawa-riku commented on resources/views/users/show.php
> +                    </div>
閉じタグズレているみたいです

2021-05-22 07:17 UTC, ichikawa-riku commented on routes/web.php
> +Route::get('/posts/{id}', 'PostController@show')->name('review.show');
ルート名をreviewにしているのはなぜでしょうか？

2021-05-22 14:53 UTC, ichikawa-riku requested changes
コメントしました。

2021-05-22 14:53 UTC, ichikawa-riku commented on app/Http/Controllers/PostController.php
> +    public function users_show()
関数名はキャメルケースが一般的です。

2021-05-22 14:53 UTC, ichikawa-riku commented on app/Http/Controllers/PostController.php
>      public function edit($id)
誰でも修正できちゃうので修正が必要そうです。

2021-05-22 14:53 UTC, ichikawa-riku commented on routes/web.php
> +    return view('posts.index');
直接Viewを呼び出し？

2021-05-22 14:53 UTC, ichikawa-riku commented on routes/web.php
> +    return view('posts.show');
直接Viewを呼び出し？

2021-05-22 14:53 UTC, ichikawa-riku commented on routes/web.php
> +    return view('posts.edit');
直接Viewを呼び出し？

2021-05-22 23:57 UTC, y-ooshima commented on routes/web.php
> +    return view('posts.edit');
不要なので削除いたします。

2021-05-22 23:57 UTC, y-ooshima commented on routes/web.php
> +    return view('posts.show');
不要なので削除いたします。

2021-05-23 00:04 UTC, y-ooshima commented on routes/web.php
> +    return view('posts.index');
コントローラから呼び出すように修正しました。
（修正内容は合っていますでしょうか。）

2021-05-26 13:16 UTC, ichikawa-riku requested changes
修正後マージOKです。

2021-05-26 13:16 UTC, ichikawa-riku commented on resources/views/users/past_show.blade.php
> +                                        <a type="button" class="btn btn-secondary" href="/mypage/show/{{ $post->id }}/edit">編集</a>
URLはroute関数を使って生成しましょう
https://qiita.com/kazuhei/items/935257b0d72fa314d461

2021-05-29 00:10 UTC, merged